[build-system]
requires = ["setuptools>=52", "wheel", "setuptools_scm>=5.0.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "VERSION.txt"
root = "."
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
